import tkinter
from tkinter import*
def hello():
	n1=e1.get()
	n2=e2.get()
	n3=e3.get()
	n4=e4.get()
	n5=e5.get()
	n6=n1+" \n"+n2+" \n"+n3+" \n"+n4+"\n "+n5
	label5.config(text=n6)
x=tkinter.Tk()
x.geometry("300x300")
label=Label(x,text="First Name: ")
label.place(x=0,y=0)
e1=Entry(x)
e1.pack()
label1=Label(x,text="Last Name: ")
label1.place(x=0,y=20)
e2=Entry(x)
e2.pack()
label2=Label(x,text="Designation: ")
label2.place(x=0,y=40)
e3=Entry(x)
e3.pack()
label3=Label(x,text="Company: ")
label3.place(x=0,y=60)
e4=Entry(x)
e4.pack()
label4=Label(x,text="Country: ")
label4.place(x=0,y=80)
e5=Entry(x)
e5.pack()
b=Button(x,text="ok",command=hello)
b.pack()
label5=Label(x)
label5.pack()
x.mainloop()
